env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - PROJECT_NAME=goimports-reviser
  - PROJECT_USER=starfishs

before:
  hooks:
    - go mod download

builds:
  - id: goimports-reviser-amd64
    binary: goimports-reviser
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.Tag={{ .Tag }}" -X "main.Commit={{ .FullCommit }}" -X "main.SourceURL={{ .GitURL }}" -X "main.GoVersion={{ .Env.GO_VERSION }}"

  - id: goimports-reviser-darwin-amd64
    binary: goimports-reviser
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "main.Tag={{ .Tag }}" -X "main.Commit={{ .FullCommit }}" -X "main.SourceURL={{ .GitURL }}" -X "main.GoVersion={{ .Env.GO_VERSION }}"

  - id: goimports-reviser-windows-amd64
    binary: goimports-reviser
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.Tag={{ .Tag }}" -X "main.Commit={{ .FullCommit }}" -X "main.SourceURL={{ .GitURL }}" -X "main.GoVersion={{ .Env.GO_VERSION }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  github:
    owner: starfishs
    name: goimports-reviser

brews:
  - name: goimports-reviser
    repository:
      owner: starfishs
      name: homebrew-tap
    url_template: "https://github.com/{{ .Env.PROJECT_USER }}/{{ .ProjectName }}/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: starfishs
      email: vyacheslavpryimak@gmail.com
    folder: Formula
    homepage: "https://github.com/starfishs/goimports-reviser"
    description: "Right imports sorting & code formatting tool"
    test: |
      system "#{bin}/goimports-reviser -version"
    install: |
      bin.install "goimports-reviser"

snapcrafts:
  - id: goimports-reviser
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    publish: true
    summary: "Right imports sorting & code formatting tool"
    description: |
      Tool for Golang to sort goimports by 3 groups: std, general and project dependencies. Also, formatting for your code will be prepared(so, you don't need to use gofmt or goimports separately).
    grade: stable
    confinement: strict
    license: MIT
